<?php
$helper = $this->helper('Magepow\ProductTags\Helper\Data');
$isEnabled = $helper->getConfigModule('general/enabled');
if(!$isEnabled) return;
$tags = $this->getTagCollection();
$sidebarTitle = $helper->getConfigModule("general/tag_sidebar_title");
$show_number_products = $helper->getConfigModule("general/show_number_products");
if($tags && $tags->getSize()){
	?>
	<div class="block block-tags block-product-tags">
	<?php if($sidebarTitle) { ?><div class="block-title"><h2><?php echo $sidebarTitle; ?></h2></div><?php } ?>
		<div class="block-content">
			<ul class="list-tags list-product-tags">
				<?php foreach($tags as $tag): ?>
				<li><a href="<?php echo $helper->getMediaUrl($tag->getIdentifier()); ?>">
                <?php 
					echo $tag->getTagTitle(); 
					if($show_number_products){
						echo " (".$tag->getNumberProducts().")";
					}
				?>
                </a>
				</li>
				<?php endforeach; ?>
			</ul>
		</div>
	</div>
	<?php
}
?>